# Generated by Django 3.2.23 on 2023-12-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('long_short', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('position', models.TextField()),
                ('margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leverage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_pnl', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
