# Generated by Django 3.2.23 on 2023-12-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('long_short', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='not_selected', max_length=29)),
                ('position', models.CharField(max_length=10)),
                ('margin', models.FloatField()),
                ('leverage', models.FloatField()),
                ('open_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('return_pnl', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
