# Generated by Django 3.2.23 on 2024-01-12 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=100, message='Content must be 500 characters or fewer.')]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(limit_value=20, message='Title must be 100 characters or fewer.')]),
        ),
        migrations.DeleteModel(
            name='UserConnection',
        ),
    ]
