# Generated by Django 3.2.23 on 2023-12-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='row_number',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
