# Generated by Django 3.2.23 on 2023-12-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_pnl_calculation_time',
        ),
    ]
