# Generated by Django 3.2.23 on 2023-12-31 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_userprofile_last_pnl_calculation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.trade'),
        ),
    ]
