# Generated by Django 3.2.23 on 2023-12-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20231208_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='long_short',
            new_name='long_or_short',
        ),
    ]
