# Generated by Django 3.2.23 on 2023-12-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_trade_row_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='portfolio_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
