# Generated by Django 3.2.23 on 2023-12-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20231229_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_realized_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_unrealized_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
