# Generated by Django 3.2.23 on 2024-01-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_blogpost_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='entry_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='exit_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='leverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='profit_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='profit_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='trade_image',
            field=models.ImageField(blank=True, null=True, upload_to='trade_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='trade_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
