# Generated by Django 3.2.23 on 2023-12-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20231229_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='profit_applied',
            field=models.BooleanField(default=False),
        ),
    ]
