# Generated by Django 3.2.23 on 2023-12-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_trade_profit_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='profit_applied',
        ),
    ]
