# Generated by Django 3.2.23 on 2023-12-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_remove_trade_profit_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_realized_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
