# Generated by Django 3.2.23 on 2024-01-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_blogpost_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='trade_image',
        ),
    ]
