# Generated by Django 3.2.23 on 2024-01-04 15:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_remove_blogpost_trade_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='trade_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
